name: Continuous Integration

on:
  push:
    branches:
      - "**"
      - "!production"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - echo "TODO"
      # - run: 'yarn install'
      # - run: 'yarn test'
